# This is the base yml for project.yml and project_production.yml
name: PlaybookShowcase
options:
  indentWidth: 2
  groupOrdering:
    - order: []
  deploymentTarget:
    iOS: 15.0
    macOS: 13.0
packages:
  Playbook:
    path: ./
targets:
  PlaybookShowcase:
    type: application
    platform: iOS
    sources: [PlaybookShowcase]
    dependencies:
      - package: Playbook
    settings:
      base:
        INFOPLIST_FILE: PlaybookShowcase/PlaybookShowcase/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.powerhrg.PlaybookShowcase
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1
